version: "3.9"
volumes:
  postgis-data:
  geoserver-data:

services:
  db:
    image: postgis/postgis
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=geor
      - POSTGRES_USER=geor
      - POSTGRES_PASSWORD=geor
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis
    ports:
      - "5431:5432"

  geoserver:
    image: kartoza/geoserver
    volumes:
        - geoserver-data:/opt/geoserver/data_dir
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    ports:
      - "8600:8080"

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=geor@kau.kr
      - PGADMIN_DEFAULT_PASSWORD=geor
    ports:
      - "5430:80"

